"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, BookOpen, Check, CheckCheck, Clock3, Download, FlaskConical, FolderOpen, GitBranch, Layers3, Plus, Search, Trash2, Upload } from "lucide-react";
import { chapters, lessons } from "@/lib/curriculum";
import { isCurrentProgress } from "@/lib/assessment-version";
import { deleteDesign, getPersistenceWarning, readDesigns, readProgress, saveDesign, validateDesign } from "@/lib/persistence";
import type { ProgressRecord, SavedDesign } from "@/lib/types";
import { Shell } from "./shell";
import { Modal, Tip } from "./ui";

function DesignPreview({ design }: { design: SavedDesign }) {
  const { nodes, edges } = design.architecture;
  const minX = Math.min(...nodes.map((n) => n.position.x));
  const minY = Math.min(...nodes.map((n) => n.position.y));
  const width = Math.max(...nodes.map((n) => n.position.x)) - minX + 180;
  const height = Math.max(...nodes.map((n) => n.position.y)) - minY + 85;
  const colors = { traffic: "#87939c", server: "#669ad1", database: "#d2a05e", cache: "#5baa8b", "load-balancer": "#8589c1", queue: "#c88799" };
  return <svg className="design-preview" viewBox={`${minX - 40} ${minY - 70} ${width + 80} ${height + 140}`} role="img" aria-label={`${design.name} architecture with ${nodes.length} components`}><defs><pattern id={`dots-${design.id}`} width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#d9e1e4" /></pattern></defs><rect x={minX - 40} y={minY - 70} width={width + 80} height={height + 140} fill={`url(#dots-${design.id})`} />{edges.map((edge) => { const a = nodes.find((n) => n.id === edge.source); const b = nodes.find((n) => n.id === edge.target); if (!a || !b) return null; return <path key={edge.id} d={`M ${a.position.x + 170} ${a.position.y + 40} C ${a.position.x + 230} ${a.position.y + 40}, ${b.position.x - 60} ${b.position.y + 40}, ${b.position.x} ${b.position.y + 40}`} fill="none" stroke="#adbdc3" strokeWidth="3" />; })}{nodes.map((node) => <g key={node.id}><rect x={node.position.x} y={node.position.y} width="170" height="80" rx="5" fill="white" stroke={colors[node.kind]} strokeWidth="2" /><rect x={node.position.x + 15} y={node.position.y + 20} width="32" height="32" rx="5" fill={colors[node.kind]} opacity="0.25" /><text x={node.position.x + 58} y={node.position.y + 38} fontSize="12" fill="#4c5963">{node.label.slice(0, 15)}</text><text x={node.position.x + 58} y={node.position.y + 56} fontSize="10" fill="#94a0a8">{node.capacity} req/s x {node.replicas}</text></g>)}</svg>;
}

export function Library({ view }: { view: "learn" | "designs" }) {
  const [progress, setProgress] = useState<ProgressRecord[]>([]);
  const [designs, setDesigns] = useState<SavedDesign[]>([]);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState<SavedDesign | null>(null);
  const upload = useRef<HTMLInputElement>(null);
  useEffect(() => {
    const refresh = () => { setProgress(readProgress()); setDesigns(readDesigns()); const warning = getPersistenceWarning(); if (warning) setError(warning); };
    refresh(); window.addEventListener("playground:storage", refresh); window.addEventListener("storage", refresh);
    return () => { window.removeEventListener("playground:storage", refresh); window.removeEventListener("storage", refresh); };
  }, []);
  const completed = new Set(progress.filter(isCurrentProgress).map((p) => p.lessonId));
  const reviewCount = progress.filter((p) => !isCurrentProgress(p) && lessons.some((lesson) => lesson.id === p.lessonId)).length;
  const next = lessons.find((l) => !completed.has(l.id)) ?? lessons[0];
  const visibleLessons = lessons.filter((l) => `${l.title} ${l.concept} ${l.chapter}`.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || filter === "completed" && completed.has(l.id) || filter === "remaining" && !completed.has(l.id)));
  const visibleDesigns = designs.filter((d) => d.name.toLowerCase().includes(query.toLowerCase()));
  const exportDesign = (design: SavedDesign) => { const url = URL.createObjectURL(new Blob([JSON.stringify(design, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${design.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "architecture"}.json`; link.click(); URL.revokeObjectURL(url); };
  const importFile = async (file?: File) => {
    if (!file) return;
    setError("");
    try { if (file.size > 1_000_000) throw new Error("Choose a design file smaller than 1 MB."); const design = validateDesign(JSON.parse(await file.text())); const outcome = saveDesign({ ...design, id: crypto.randomUUID(), updatedAt: new Date().toISOString() }); if (!outcome.ok) throw new Error(outcome.error); setDesigns(readDesigns()); }
    catch (caught) { setError(caught instanceof SyntaxError ? "This file is not valid JSON." : caught instanceof Error ? caught.message : "This design could not be imported."); }
    if (upload.current) upload.current.value = "";
  };
  return <Shell><header className="topbar"><div className="breadcrumb"><span>Personal workspace</span><ArrowRight size={12} /><span>{view === "learn" ? "Learning path" : "My designs"}</span></div><span className="topbar-note"><span className="tiny-dot" />Learning by doing</span></header><div className="library-page"><div className="library-heading"><div><span className="eyebrow">{view === "learn" ? "FROM FIRST REQUEST TO LAUNCH DAY" : "YOUR ARCHITECTURE COLLECTION"}</span><h1>{view === "learn" ? "Your learning path" : "My designs"}</h1><p>{view === "learn" ? "Twelve practical missions. One connected understanding of systems." : "Experiments worth keeping. Systems worth revisiting."}</p></div>{view === "learn" ? <Link className="button primary" href={`/learn/${next.id}`}>{progress.length ? "Continue learning" : "Start learning"}<ArrowRight size={16} /></Link> : <div className="library-heading-actions"><button className="button" onClick={() => upload.current?.click()}><Upload size={15} />Import</button><Link href="/sandbox" className="button primary"><Plus size={16} />New design</Link><input className="sr-only" ref={upload} type="file" accept=".json,application/json" aria-label="Import design file" onChange={(e) => importFile(e.target.files?.[0])} /></div>}</div>
    {view === "learn" && <div className="learning-overview"><div><span className="overview-icon"><BookOpen size={20} /></span><span><strong>{completed.size}<small> / {lessons.length}</small></strong><span>Lessons completed</span></span></div><div><span className="overview-icon violet"><Layers3 size={20} /></span><span><strong>{chapters.length}</strong><span>Connected chapters</span></span></div><div><span className="overview-icon amber"><Clock3 size={20} /></span><span><strong>8-15<small> min</small></strong><span>One focused experiment</span></span></div><div className="learning-progress"><span>{Math.round(completed.size / lessons.length * 100)}% complete</span><div className="progress-track"><div style={{ width: `${completed.size / lessons.length * 100}%` }} /></div></div></div>}
    <div className="library-toolbar"><label className="search-field"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={view === "learn" ? "Find a lesson or concept..." : "Search your designs..."} aria-label={view === "learn" ? "Search lessons" : "Search designs"} /></label>{view === "learn" ? <div className="segmented" aria-label="Filter lessons">{[{ id: "all", text: "All lessons" }, { id: "remaining", text: "Remaining" }, { id: "completed", text: "Completed" }].map((item) => <button key={item.id} aria-pressed={filter === item.id} className={filter === item.id ? "active" : ""} onClick={() => setFilter(item.id)}>{item.text}</button>)}</div> : <span className="muted">{designs.length} saved {designs.length === 1 ? "design" : "designs"}</span>}</div>
    {view === "learn" && reviewCount > 0 && <div className="model-update-note" role="status">{reviewCount} earlier {reviewCount === 1 ? "completion needs" : "completions need"} review after the routing and grading update. Saved designs are unchanged.</div>}
    {error && <div className="inline-error" role="alert">{error}</div>}
    {view === "learn" ? <div className="curriculum-chapters">{chapters.map((chapter, index) => { const items = visibleLessons.filter((l) => l.chapter === chapter); return !!items.length && <section id={`chapter-${index}`} className="curriculum-chapter" key={chapter}><div className="curriculum-chapter-heading"><span className="chapter-index">0{index + 1}</span><div><span className="eyebrow">CHAPTER {index + 1}</span><h2>{chapter}</h2></div><span className="chapter-completion">{lessons.filter((l) => l.chapter === chapter && completed.has(l.id)).length} / 3 complete</span></div><div className="lesson-list">{items.map((lesson) => <Link href={`/learn/${lesson.id}`} className={`lesson-row ${completed.has(lesson.id) ? "lesson-row-complete" : ""}`} key={lesson.id}><span className="lesson-row-number">{completed.has(lesson.id) ? <Check size={16} /> : String(lesson.number).padStart(2, "0")}</span><span className="lesson-row-title"><strong>{lesson.title}</strong><small>{lesson.subtitle}</small></span><span className={`difficulty ${lesson.difficulty.toLowerCase()}`}>{lesson.difficulty}</span><span className="lesson-row-time"><Clock3 size={13} />{lesson.minutes} min</span><ArrowRight size={17} /></Link>)}</div></section>; })}{!visibleLessons.length && <div className="library-empty"><Search size={27} /><h2>No matching lessons</h2><p>Try another search or lesson filter.</p><button className="button" onClick={() => { setQuery(""); setFilter("all"); }}>Clear filters</button></div>}</div> : <>{visibleDesigns.length ? <div className="design-grid">{visibleDesigns.map((design) => <article className="design-card" key={design.id}><Link href={`/sandbox?design=${encodeURIComponent(design.id)}`} tabIndex={-1}><DesignPreview design={design} /></Link><div className="design-card-body"><Link href={`/sandbox?design=${encodeURIComponent(design.id)}`}><h2>{design.name}</h2></Link><p><GitBranch size={12} />{design.architecture.nodes.length} components<span />{design.workload.requestRate} req/s</p><div className="design-card-footer"><span>{new Date(design.updatedAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</span><div><Tip label="Export design"><button className="icon-button" aria-label={`Export ${design.name}`} onClick={() => exportDesign(design)}><Download size={15} /></button></Tip><Tip label="Delete design"><button className="icon-button" aria-label={`Delete ${design.name}`} onClick={() => setDeleting(design)}><Trash2 size={15} /></button></Tip></div></div></div></article>)}</div> : <div className="library-empty"><span className="empty-illustration"><FolderOpen size={42} strokeWidth={1.2} /></span><h2>{query ? "No matching designs" : "Your next idea starts here."}</h2><p>{query ? "Try another design name." : "Saved architectures will appear in your personal collection."}</p><Link href="/sandbox" className="button primary"><FlaskConical size={16} />Open sandbox</Link></div>}</>}
    </div><Modal open={!!deleting} onOpenChange={(open) => { if (!open) setDeleting(null); }} title="Delete this design?" description={`Remove ${deleting?.name ?? "this design"} from your saved collection? This cannot be undone.`}><div className="modal-actions"><button className="button" onClick={() => setDeleting(null)}>Keep design</button><button className="button danger-button" onClick={() => { if (!deleting) return; const outcome = deleteDesign(deleting.id); if (!outcome.ok) setError(outcome.error); setDesigns(readDesigns()); setDeleting(null); }}><Trash2 size={15} />Delete design</button></div></Modal></Shell>;
}
